### ISSUE TITLE
Adding Classes to the HTML Tag fails

### ISSUE THREAD

**Issue by jacmaes** [dmolsen/Detector#11]
Adding the <?=Detector::createHTMLList($ua)?>" to the HTML tag as instructed in the tutorial (https://github.com/dmolsen/Detector/wiki/Pushing-Detector-Data-to-the-Browser-Tutorial) produces an error in Detector 0.85: "Call to undefined method Detector::createHTMLList()"

You can check it on your own demo page:
http://detector.dmolsen.com/demo/classlist/

For that matter, the rest of the demos on that page do not work either.

**Comment by dmolsen** [comment]
Wow, that's out of date. Thanks for the heads up.

**Comment by dmolsen** [comment]
Fixed the examples and documentation. Again, thanks.

**Comment by jacmaes** [comment]
No problem. Do I need to update Detector? The current version still seems to be 0.85...

**Comment by dmolsen** [comment]
The feature has been supported by a separate file since Detector  0.7.0. You can simply [grab that file](https://github.com/dmolsen/Detector/blob/master/lib/Detector/lib/helpers/detectorHelper.php) for now. I was trying to push out v0.9 today but I got held up. I'd hate for you to pull it to only find that I tweaked something else. I should have held off pushing out my changes to the repo. Sorry.
