### ISSUE TITLE
Per-request tests not running/updating $ua?

### ISSUE THREAD

**Issue by rtrvrtg** [dmolsen/Detector#9]
I've been having issues getting the per-request tests to be saved to the session on every request.  This seemed to work in 0.7.1 but seems to have stopped working as of 0.8.0.  I'll have to test this to make sure.
This might be the case with my Drupal integration module, but I'm not sure if it's the module, the library or Drupal that's the root of the issues.

For example, the supplied screenattributes test doesn't change windowWidth or windowHeight variables regardless of browser size changes and how many times the browser is refreshed.  I suspect that the cookie is not being updated or read on load or something along these lines, or that the session is not being refreshed in some other way.

Has anything relating to the cookie processing changed since 0.7.1?

**Comment by dmolsen** [comment]
Yeah, I mucked with the cookies in 0.8.0 but thought the tests all passed. Let me review and see what's going on. Oh, it might be related to features.js.php. Not sure how you have that set-up but it can end up living outside of the main library directory. Make sure you've updated that too.

**Comment by dmolsen** [comment]
After poking around I think this issue is related to features.js.php. Their are two changes in v0.8.0 related to it. First is that features.js.php itself has a flag to turn off some of the functionality of Detector. The second is that the config includes a var to set the public location of features.js.php (e.g. yoursite.com/path/to/features.js.php). One or both may be causing the issue you're seeing. Make sure you copy in the new version out of Detector/util/js-include and make sure to update the config. Sorry 'bout that.
